apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/pradipmengal/opbackend:v1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: react-config
            - secretRef:
                name: db-secret
      imagePullSecrets:
        - name: dockerhub-secret
